Id: d5d546b5-4645-42bd-8ae4-d7339f2267c5
Name: config-management-service
CreatedDate: 
LastUpdated: 
OwnerId: cafe-OE867l_C_A
ServiceVersion: 
ServiceAttributes: 
EndPoints: 
ServiceType:
  serviceTypeId: com.vmware.csp.component.cafe.config.management
  productId: com.vmware.csp.component
  typeId: cafe.config.management
  serviceName: 
NameMsgKey: 

