Id: 2e5b0969-32b8-4932-99df-05deb7f9771d
Name: endpoint-configuration-service
CreatedDate: 
LastUpdated: 
OwnerId: cafe-OE867l_C_A
ServiceVersion: 
ServiceAttributes: 
EndPoints: 
ServiceType:
  serviceTypeId: com.vmware.csp.core.endpoint.configuration
  productId: com.vmware.csp.core
  typeId: endpoint.configuration
  serviceName: 
NameMsgKey: 

