EndpointUrl: https://cava-n-80-154.eng.vmware.com/config-management-service/api/status
Id: d5d546b5-4645-42bd-8ae4-d7339f2267c5
LastUpdated: 2019-06-24 14:18:12.900000
Name: config-management-service
NotAvailable: false
ServiceStatus:
  defaultServiceEndpointType: com.vmware.csp.component.cafe.config.management.api
  errorMessage: null
  identityCertificateInfo: null
  initialized: true
  serviceInitializationStatus: REGISTERED
  serviceName: config-management-service
  serviceRegistrationId: d5d546b5-4645-42bd-8ae4-d7339f2267c5
  solutionUser: cafe-OE867l_C_A
  sslCertificateInfo:
    identityCertificateExists: true
    issuerName: CN=VMware vRA,OU=Unit,O=Organisation,L=PA,ST=ON,C=US
    notValidAfter: 2024-06-22 13:53:42
    notValidBefore: 2019-06-24 13:53:42
    principalName: CN=VMware vRA,OU=Unit,O=Organisation,L=PA,ST=ON,C=US
    thumbprint: 80:0D:D5:BF:9F:6E:37:74:1A:10:F4:95:ED:12:D2:91:4C:53:00:26
  startedTime: 2019-06-24 14:18:13.573000
TypeId: com.vmware.csp.component.cafe.config.management
