Id: d5d546b5-4645-42bd-8ae4-d7339f2267c5
Name: config-management-service
TypeId: com.vmware.csp.component.cafe.config.management
NotAvailable: false
LastUpdated: 2019-06-24T14:18:12.9000000Z
EndpointUrl: https://cava-n-80-154.eng.vmware.com/config-management-service/api/status
ServiceStatus:
  initialized: true
  serviceName: config-management-service
  solutionUser: cafe-OE867l_C_A
  startedTime: 2019-06-24T14:18:13.5730000Z
  serviceInitializationStatus: REGISTERED
  errorMessage: 
  identityCertificateInfo: 
  serviceRegistrationId: d5d546b5-4645-42bd-8ae4-d7339f2267c5
  sslCertificateInfo:
    identityCertificateExists: true
    issuerName: CN=VMware vRA,OU=Unit,O=Organisation,L=PA,ST=ON,C=US
    principalName: CN=VMware vRA,OU=Unit,O=Organisation,L=PA,ST=ON,C=US
    notValidBefore: 2019-06-24T13:53:42.0000000Z
    notValidAfter: 2024-06-22T13:53:42.0000000Z
    thumbprint: 80:0D:D5:BF:9F:6E:37:74:1A:10:F4:95:ED:12:D2:91:4C:53:00:26
  defaultServiceEndpointType: com.vmware.csp.component.cafe.config.management.api

