Id: 2e5b0969-32b8-4932-99df-05deb7f9771d
Name: endpoint-configuration-service
TypeId: com.vmware.csp.core.endpoint.configuration
NotAvailable: false
LastUpdated: 2019-06-24T14:17:38.4820000Z
EndpointUrl: https://cava-n-80-154.eng.vmware.com/endpoint-configuration-service/api/status
ServiceStatus:
  initialized: true
  serviceName: endpoint-configuration-service
  solutionUser: cafe-OE867l_C_A
  startedTime: 2019-06-24T14:17:39.4060000Z
  serviceInitializationStatus: REGISTERED
  errorMessage: 
  identityCertificateInfo: 
  serviceRegistrationId: 2e5b0969-32b8-4932-99df-05deb7f9771d
  sslCertificateInfo:
    identityCertificateExists: true
    issuerName: CN=VMware vRA,OU=Unit,O=Organisation,L=PA,ST=ON,C=US
    principalName: CN=VMware vRA,OU=Unit,O=Organisation,L=PA,ST=ON,C=US
    notValidBefore: 2019-06-24T13:53:42.0000000Z
    notValidAfter: 2024-06-22T13:53:42.0000000Z
    thumbprint: 80:0D:D5:BF:9F:6E:37:74:1A:10:F4:95:ED:12:D2:91:4C:53:00:26
  defaultServiceEndpointType: com.vmware.csp.core.endpoint.configuration.api

