Callbacks: null
CatalogItemType: Ansible
DateCreated: 2019-06-24 14:18:36.025000
Description: Represents Config Management catalog items of type Ansible
Forms: null
IconId: cafe_default_icon_genericCatalogItem
Id: 1961b79e-3134-4424-9036-445d6db54520
IsNoteworthy: false
LastUpdatedDate: null
Name: Ansible Config Mgmt Component
Organization: null
OutputResourceType: Ansible
ProviderBinding:
  bindingId: ConfigManagement.Ansible.ConfigMgmt.Component
  providerRef:
    id: d5d546b5-4645-42bd-8ae4-d7339f2267c5
    label: Configuration Management Service
Quota: 0
Requestable: false
Service: null
Status: PUBLISHED
Version: 0
