Callbacks:
  details: false
  list: false
CostFeatures:
  lease: false
  leaseCost: false
Description: Configuration Management Resource type
Forms:
  catalogResourceInfoHidden: true
  details: null
Id: ConfigManagement.Root
ListDescendantTypesSeparately: null
ListView: null
Name: Configuration Management
PluralizedName: Configuration Management
Primary: true
ProviderTypeId: com.vmware.csp.component.cafe.config.management
Schema:
  classId: ConfigManagement.Root.Schema
  typeFilter: null
ShowChildrenOutsideParent: false
Status: ACTIVE
