Id: COMPOSITION_SERVICE_APPLICATION_ARCHITECT
Name: Application Architect
Description: Assembles and manages composite blueprints for the tenant.
Type: TenantRole
AssignedPermissions:
- id: GUI_DESIGNER
  name: Access Blueprint and Blueprint Component Design GUI
  description: Access the blueprint and blueprint component design GUI.
  prereqAdminPermissions: 
- id: CATALOG_AUTHOR_TENANT
  name: Catalog Tenant-level Author
  description: Create, update and publish services, catalog items and actions shared across a Tenant.
  prereqAdminPermissions: 
- id: CONTENT_CONSUME_TENANT
  name: Consume content tenant wide
  description: Consume and export content in the tenant context.
  prereqAdminPermissions: 
- id: COMPOSITION_SERVICE_CONSUME_BLUEPRINTS
  name: Consume Composite Blueprints
  description: View composite blueprints belonging to the tenant.
  prereqAdminPermissions: 
- id: COMPOSITION_SERVICE_AUTHOR_COMPONENT_TYPES
  name: Publish Blueprint Components
  description: Publish blueprint components for reuse in the tenant.
  prereqAdminPermissions: 
- id: COMPOSITION_SERVICE_CONSUME_COMPONENT_TYPES
  name: Consume Published Blueprint Components
  description: View and reuse published blueprint components belonging to the tenant.
  prereqAdminPermissions: 
- id: COMPOSITION_SERVICE_AUTHOR_BLUEPRINTS
  name: Author Composite Blueprints
  description: Assemble, edit and publish composite blueprints for the tenant.
  prereqAdminPermissions: 
- id: CONTENT_AUTHOR_TENANT
  name: Author content tenant wide
  description: Create, edit ,import and publish content in the tenant context.
  prereqAdminPermissions: 

