BindingId: Infrastructure.Machine.Action.CancelReconfigure
Callbacks: null
Description: Cancel reconfigure on a machine.
Entitleable: true
ExternalId: Infrastructure.Machine.Action.CancelReconfigure
Forms: null
IconId: machineCancelReconfigure.png
Id: 03888b7a-aec6-47c6-8ec3-49b402758c08
LifecycleAction: null
Name: Cancel Reconfigure
ProviderTypeRef:
  id: com.vmware.csp.iaas.blueprint.service
  label: Infrastructure Service
RequestSchema:
  classId: resourceActionRequest
  typeFilter: Infrastructure.Machine.Action.CancelReconfigure
Status: PUBLISHED
TargetCriteria:
  subClauses:
  - leftOperand:
      path: CancelReconfigure
      type: path
    operator:
      type: isDefined
    rightOperand: null
    type: expression
  - leftOperand:
      path: CancelReconfigure
      type: path
    operator:
      type: equals
    rightOperand:
      type: constant
      value:
        type: boolean
        value: true
    type: expression
  type: and
TargetResourceTypeRef:
  id: Infrastructure.Machine
  label: Machine
organization: null
