Id: 03888b7a-aec6-47c6-8ec3-49b402758c08
Name: Cancel Reconfigure
ExternalId: Infrastructure.Machine.Action.CancelReconfigure
Description: Cancel reconfigure on a machine.
IconId: machineCancelReconfigure.png
TargetCriteria:
  type: and
  subClauses:
  - type: expression
    operator:
      type: isDefined
    leftOperand:
      type: path
      path: CancelReconfigure
    rightOperand: 
  - type: expression
    operator:
      type: equals
    leftOperand:
      type: path
      path: CancelReconfigure
    rightOperand:
      type: constant
      value:
        type: boolean
        value: true
TargetResourceTypeRef:
  id: Infrastructure.Machine
  label: Machine
Status: PUBLISHED
Entitleable: true
organization: 
RequestSchema:
  classId: resourceActionRequest
  typeFilter: Infrastructure.Machine.Action.CancelReconfigure
Forms: 
Callbacks: 
LifecycleAction: 
BindingId: Infrastructure.Machine.Action.CancelReconfigure
ProviderTypeRef:
  id: com.vmware.csp.iaas.blueprint.service
  label: Infrastructure Service

