BindingId: Infrastructure.Machine.Action.ExecuteReconfigure
Callbacks: null
Description: Infrastructure execute reconfigure.
Entitleable: true
ExternalId: Infrastructure.Machine.Action.ExecuteReconfigure
Forms:
  catalogRequestInfoHidden: true
  requestDetails:
    formId: Infrastructure.Machine-Resource.Action.Details
    type: external
  requestFormScale: BIG
  requestPostApproval: null
  requestPreApproval: null
  requestSubmission:
    formId: Infrastructure.Machine-Resource.Action.Submit
    type: external
IconId: machineExecuteReconfigure.png
Id: 879083c2-69b9-4fc0-8313-10a958bba0c6
LifecycleAction: null
Name: Execute Reconfigure
ProviderTypeRef:
  id: com.vmware.csp.iaas.blueprint.service
  label: Infrastructure Service
RequestSchema:
  classId: resourceActionRequest
  typeFilter: Infrastructure.Machine.Action.ExecuteReconfigure
Status: PUBLISHED
TargetCriteria:
  subClauses:
  - leftOperand:
      path: ExecuteReconfigure
      type: path
    operator:
      type: isDefined
    rightOperand: null
    type: expression
  - leftOperand:
      path: ExecuteReconfigure
      type: path
    operator:
      type: equals
    rightOperand:
      type: constant
      value:
        type: boolean
        value: true
    type: expression
  type: and
TargetResourceTypeRef:
  id: Infrastructure.Machine
  label: Machine
organization: null
