Id: 879083c2-69b9-4fc0-8313-10a958bba0c6
Name: Execute Reconfigure
ExternalId: Infrastructure.Machine.Action.ExecuteReconfigure
Description: Infrastructure execute reconfigure.
IconId: machineExecuteReconfigure.png
TargetCriteria:
  type: and
  subClauses:
  - type: expression
    operator:
      type: isDefined
    leftOperand:
      type: path
      path: ExecuteReconfigure
    rightOperand: 
  - type: expression
    operator:
      type: equals
    leftOperand:
      type: path
      path: ExecuteReconfigure
    rightOperand:
      type: constant
      value:
        type: boolean
        value: true
TargetResourceTypeRef:
  id: Infrastructure.Machine
  label: Machine
Status: PUBLISHED
Entitleable: true
organization: 
RequestSchema:
  classId: resourceActionRequest
  typeFilter: Infrastructure.Machine.Action.ExecuteReconfigure
Forms:
  catalogRequestInfoHidden: true
  requestFormScale: BIG
  requestSubmission:
    type: external
    formId: Infrastructure.Machine-Resource.Action.Submit
  requestDetails:
    type: external
    formId: Infrastructure.Machine-Resource.Action.Details
  requestPreApproval: 
  requestPostApproval: 
Callbacks: 
LifecycleAction: 
BindingId: Infrastructure.Machine.Action.ExecuteReconfigure
ProviderTypeRef:
  id: com.vmware.csp.iaas.blueprint.service
  label: Infrastructure Service

