Id: 522a35b5-138c-4731-aeb6-7093f51c9994
Name: Reconfigure
ExternalId: Infrastructure.Network.LoadBalancer.NSX.Action.Reconfigure
Description: Reconfigure a load balancer.
IconId: icon_reconfigure
TargetCriteria: 
TargetResourceTypeRef:
  id: Infrastructure.Network.LoadBalancer.NSX
  label: Load Balancer
Status: PUBLISHED
Entitleable: true
organization: 
RequestSchema:
  classId: resourceActionRequest
  typeFilter: Infrastructure.Network.LoadBalancer.NSX.Action.Reconfigure
Forms:
  catalogRequestInfoHidden: true
  requestFormScale: BIG
  requestSubmission:
    type: external
    formId: Infrastructure.Network.LoadBalancer.NSX-Resource.Action.Submit
  requestDetails:
    type: external
    formId: Infrastructure.Network.LoadBalancer.NSX-Resource.Action.Details
  requestPreApproval: 
  requestPostApproval: 
Callbacks:
  validate: true
  rollback: false
  itemInformation: false
  itemInitialize: false
LifecycleAction: Reconfigure
BindingId: Infrastructure.Network.LoadBalancer.NSX.Action.Reconfigure
ProviderTypeRef:
  id: com.vmware.csp.component.network.service
  label: Network Service

